### ISSUE TITLE
3.71.2 Use Case Roles

### ISSUE THREAD

**Issue by gregoriocanal** [IHE/IT-Infrastructure#103]
-this section should be Actor Roles section.

**Comment by msmock** [comment]
Hhm. I always use the XUA part of Volume 2 as template. We should discuss this with John in the meeting this week.

**Comment by JohnMoehrke** [comment]
The supplement template does change over time. So we do need to check with the guidance and templates occasionally. The current guidance to supplement writers is https://wiki.ihe.net/index.php/Writing_Technical_Frameworks_and_Supplements

here is the supplement template https://drive.google.com/drive/folders/13nsG6u3V--lQgCXCZlt0M73-oRgSXE9q

yes, that section should be called "Actor Roles".  The reason is that we started to use role names rather than actor names. This change is not all that helpful with simple transactions, but becomes more useful when a transaction is used in multiple profiles for multiple profile specific actors (e.g. ITI-18)
