### ISSUE TITLE
IUA use of extensions / CP-ITI-1149

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/IT-Infrastructure#46]
to prevent name collision between multiple uses

**Comment by lcmaas** [comment]
- move non-standard top-level JWT claims into an "IUA Authorization Extension Object"
- the IUA Authorization Extension Object is used as the value of of a profile-defined key (e.g. `ihe_iua`) in the top-level `extensions` object (per current UDAP model) as per example below.
- use simple key names instead of URNs (lower case, underscore instead of hyphens)
- limit use of complex datatypes; strings are preferred
- add version key to authorization object (datatype not constrained, could be a date, number, or URN, etc.)

Example:
```
    {
      "iss": "{issuer_uri}",
      ...
      "extensions" : {
        "ihe_iua" : {
           "version":"2020-05-01",
           "subject_id":"John Iyouay",
           ...
         }
      }
    }
```

Note: grouping the profile-specific claims like this is the current preferred UDAP extension mechanism. In addition to eliminating key name collisions, this allows relying parties parsing the JWT to easily identify which profile(s) are being used (based on the key names in the top-level `extensions` object) and handle the profile(s) that they support.

**Comment by walcovanloon** [comment]
@lcmaas : in which UDAP revision is the "namespaced" extension mechanism described? http://www.udap.org/udap-client-authorization-grants.html still uses the old scheme.

**Comment by walcovanloon** [comment]
Note that OpenID Connect also provides a mechanism for annotation of extension claims: https://openid.net/specs/openid-connect-core-1_0.html#AggregatedDistributedClaims

**Comment by JohnMoehrke** [comment]
@lcmaas although we accepted the pull request, we are still very interested in your feedback. We will re-open if need to.
