### ISSUE TITLE
IUA consent pointer more FHIR friendly

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/IT-Infrastructure#47]

**Comment by lcmaas** [comment]
based on stakeholder feedback I have received from the UDAP community, consider including a literal FHIR resource URI for consent documents instead of (or in addition to) the current `docid`. For example, another group that I work with has an `acp_reference` key in their authorization extension object with a value equal to an array of one or more DocumentReference or Consent resource URIs. 

Although this is very FHIR-specific, this approach is consistent with the concept in #48
