### ISSUE TITLE
IUA use of FHIR datatype for codes

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/IT-Infrastructure#48]

**Comment by lcmaas** [comment]
- Use FHIR code when system is fixed by the profile. (1)
- Use FHIR [Coding](http://hl7.org/fhir/datatypes.html#codesystem) datatype when system is not fixed. (2)

Note 1: code should be preferred over coding for simplicity; so need to assess where fixed system is sufficient.
Note 2: Coding datatype has optionality; recommend requiring system 1..1, code 1..1

**Comment by JohnMoehrke** [comment]
should this be closed?
