### ISSUE TITLE
IUA terminology alignment (Authorization token)

### ISSUE THREAD

**Issue by lcmaas** [IHE/IT-Infrastructure#49]
[Edit: Hmmm. In reading through section 3.72, I now realize that the workflows defined in the IUA document do not follow the assertion frameworks proposed in RFCs 7521-7523, and my earlier comment was based on the mistaken assumption that those workflows were being followed (as used in UDAP, for example) so I have deleted the earlier comment and replaced with the following.]

In the current IUA workflows, the entity that provides the signed assertions is called the Authorization Server, but this is not the way this term is generally used in the OAuth 2.0 arena. As this actor is providing the assertions that contain the authorization metadata needed to make authorization decisions, then this actor is associated with the client and not the resource server. Other frameworks would call this the Client Token Service or Assertion Provider or something similar, but not call it the Authorization Server.

The term Authorization Server should represent the entity associated with the resource server that evaluates the assertions provided by clients to determine if an access token should be granted. Instead, the authorization token is presented directly to the resource server without a separate access token, such that the role of the Authorization Server (in the OAuth 2.0 sense) has actually been rolled into the resource server.

I see that how the IUA workflow does parallel how XUA is used in SOAP transactions, but this is not the way that FHIR/OAuth environments generally work. For example, the IUA model has not OAuth 2.0 token endpoint.

**Comment by msmock** [comment]
I do not agree to your conclusions. OAuth was initially designed with only the resource owner role implicitly assuming, that the resource owner is the user. If you see how Google and facebook uses OAuth, you'll find this close to the initially concept: Coming from some 3rd party application a user is delegated to google or facebook, must authenticate with google or facebook and may give consent for the 3rd party application to access the users data on google or facebook. 

In a health scenario (or many other business scenarios) the user typically is not the resource owner. If you have access to specific data us typically defined by the company or the patient, as we have in Swiss national EPR. 

To my understanding the authorization is split: First, the user first has to give consent to allow the application to access data (classes) on behalf of the user. Second, the access to specific data is controlled by the backend (resource server) enforcing the company policies, or those defined by the patient. 

To my understanding any attempt to handle both of the above steps in an OAuth like Authorization Server must fail, since in health scenarios the user typically is not the resource owner of the data stored in the Resource Server.

**Comment by lcmaas** [comment]
yes, the OAuth 2.0 term `resource owner` is outdated. I'd say this term should not be taken literally as the legal owner of the data. For healthcare workflows in the U.S., at least, the `resource owner` actor in the authorization code flow is commonly understood to be an end user who has the right to authorize the requested scopes for an authorization code grant. 

This is inline with the discussions in IETF around this term. In fact, they've added a definition to the [draft OAuth 2.1 spec](https://tools.ietf.org/html/draft-parecki-oauth-v2-1-02) to clarify exactly what `resource owner` means as this term was not actually defined in the OAuth 2.0 spec. I've excerpted the definition here -- note there is no mention of legal ownership of the data:

   "resource owner":  An entity capable of granting access to a
      protected resource.  When the resource owner is a person, it is
      referred to as an end-user.  This is sometimes abbreviated as
      "RO".

So, I would say that the user is typically the `resource owner` in the OAuth sense, if not the legal sense. Regardless, I'm not following why this matters for the consent/control split. Authorization Servers must understand what a user is permitted to authorize and communicate enough information to the resource server so that the resource server can enforce its policies. This can be accomplished in many ways, but is typically done via [token introspection](https://tools.ietf.org/html/rfc7662) when the Authorization server and Resource server are not tightly linked.

**Comment by kwboone** [comment]
If such must fail, how do you explain the fact that it has been implemented as described, in that the user is able to authorize apps on their behalf.

A tweet is a resource.  I have access to certain tweets, but I am not the owner of said tweets.  OAuth allows me to grant the same access I have to those tweets to an app acting on my behalf.  Resource ownership is not essential in OAuth, unless you perhaps include access rights as the resource “owned”, in which case, perhaps thats what is being granted authorisation to use.  

The point is, it works, authorizations can and are granted by users to resources without ownership of resources being considered.

    Keith

On Jun 11, 2020, at 6:56 AM, Martin Smock <notifications@github.com> wrote:

﻿
I do not agree to your conclusions. OAuth was initially designed with only the resource owner role implicitly assuming, that the resource owner is the user. If you see how Google and facebook uses OAuth, you'll find this close to the initially concept: Coming from some 3rd party application a user is delegated to google or facebook, must authenticate with google or facebook and may give consent for the 3rd party application to access the users data on google or facebook.

In a health scenario (or many other business scenarios) the user typically is not the resource owner. If you have access to specific data us typically defined by the company or the patient, as we have in Swiss national EPR.

To my understanding the authorization is split: First, the user first has to give consent to allow the application to access data (classes) on behalf of the user. Second, the access to specific data is controlled by the backend (resource server) enforcing the company policies, or those defined by the patient.

To my understanding any attempt to handle both of the above steps in an OAuth like Authorization Server must fail, since in health scenarios the user typically is not the resource owner of the data stored in the Resource Server.

**Comment by msmock** [comment]
Seems to me we are in line on this topic, if we agree upon that in health scenario the user (e.g. a healthcare professional) is in most cases not the owner of the data (patient related documents) and the decision if he may access patient data may be granted by the Authorization Server, while the decision if she may access to a specifc document is done be the resource server based on other characteristics confidentiality code, role, etc. 

Or using the tweet example: the user may grant access for an application to access tweets and display the tweets, but not to specific tweets in general, because that is typically done by other methods on server side.
